"""Event definitions used throughout the backtesting workflow."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime


class Event:
    """Base class for all events."""

    type: str


@dataclass(frozen=True)
class MarketEvent(Event):
    """Carries the newest market bar into the event loop."""

    symbol: str
    timestamp: datetime
    close: float
    volume: float
    type: str = "MARKET"


@dataclass(frozen=True)
class SignalEvent(Event):
    """Trading signal emitted by a strategy module."""

    symbol: str
    timestamp: datetime
    signal_type: str
    strength: float = 1.0
    type: str = "SIGNAL"


@dataclass(frozen=True)
class OrderEvent(Event):
    """Order request generated by the portfolio from a signal."""

    symbol: str
    timestamp: datetime
    order_type: str
    quantity: int
    direction: str
    type: str = "ORDER"


@dataclass(frozen=True)
class FillEvent(Event):
    """Represents an executed order including realistic transaction costs."""

    symbol: str
    timestamp: datetime
    quantity: int
    direction: str
    fill_cost: float
    commission: float
    slippage: float
    type: str = "FILL"

    @property
    def signed_quantity(self) -> int:
        """Return quantity with sign convention (+buy, -sell)."""
        return self.quantity if self.direction.upper() == "BUY" else -self.quantity
